version: 2

orbs:
    # TODO: Liquibase orb
    # TODO: Command line orb? e.g. .NET
  
executors:  
  deploy-executor:
    docker:
      - image: circleci/python:2.7-jessie
      
# TODO: need any use params or just environment vars for db instance / creds?
parameters:
    SOME_PARAM:
        type: string
        default: "blarg"

jobs:
    build:
        executor: deploy-executor
        steps:
        - checkout
        
    step1:
        executor: deploy-executor
        steps:
        - run:
            name: first steps       

workflows:
    version: 2
    build_and_test:
        jobs:
        - build
        - step1:
            requires:
                - build 
