version: 2

orbs:
    # TODO: Liquibase orb
    win: circleci/windows@2.2.0
      
# TODO: need any use params or just environment vars for db instance / creds?
parameters:
    SOME_PARAM:
        type: string
        default: "blarg"

jobs:
    build:
        executor: win/default
        steps:
        - checkout
        
    step1:
        executor: win/default 
        steps:
        - run:
            name: first steps       

workflows:
    version: 2
    build_and_test:
        jobs:
        - build
        - step1:
            requires:
                - build 
